package com.smart.models;
// Generated Apr 25, 2016 10:55:45 AM by Hibernate Tools 5.0.0.CR1



/**
 * AssetsHardwareMonitorSize generated by hbm2java
 */
public class AssetsHardwareMonitorSize  implements java.io.Serializable {


     private Integer id;
     private int size;

    public AssetsHardwareMonitorSize() {
    }

    public AssetsHardwareMonitorSize(int size) {
       this.size = size;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getSize() {
        return this.size;
    }
    
    public void setSize(int size) {
        this.size = size;
    }




}


