package com.smart.models;
// Generated Apr 25, 2016 10:55:45 AM by Hibernate Tools 5.0.0.CR1



/**
 * AssetsHardwarePlatform generated by hbm2java
 */
public class AssetsHardwarePlatform  implements java.io.Serializable {


     private Integer platformId;
     private String platform;
     private String comments;

    public AssetsHardwarePlatform() {
    }

	
    public AssetsHardwarePlatform(String platform) {
        this.platform = platform;
    }
    public AssetsHardwarePlatform(String platform, String comments) {
       this.platform = platform;
       this.comments = comments;
    }
   
    public Integer getPlatformId() {
        return this.platformId;
    }
    
    public void setPlatformId(Integer platformId) {
        this.platformId = platformId;
    }
    public String getPlatform() {
        return this.platform;
    }
    
    public void setPlatform(String platform) {
        this.platform = platform;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


