package com.smart.models;
// Generated Apr 25, 2016 10:55:45 AM by Hibernate Tools 5.0.0.CR1



/**
 * AssetsSoftwarePlatform generated by hbm2java
 */
public class AssetsSoftwarePlatform  implements java.io.Serializable {


     private Integer id;
     private String assetsSoftwareType;

    public AssetsSoftwarePlatform() {
    }

    public AssetsSoftwarePlatform(String assetsSoftwareType) {
       this.assetsSoftwareType = assetsSoftwareType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAssetsSoftwareType() {
        return this.assetsSoftwareType;
    }
    
    public void setAssetsSoftwareType(String assetsSoftwareType) {
        this.assetsSoftwareType = assetsSoftwareType;
    }




}


