package com.smart.models;
// Generated Apr 25, 2016 10:55:45 AM by Hibernate Tools 5.0.0.CR1



/**
 * AssetsHardwareStatus generated by hbm2java
 */
public class AssetsHardwareStatus  implements java.io.Serializable {


     private Integer id;
     private String assetsHardwareStatus;

    public AssetsHardwareStatus() {
    }

    public AssetsHardwareStatus(String assetsHardwareStatus) {
       this.assetsHardwareStatus = assetsHardwareStatus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAssetsHardwareStatus() {
        return this.assetsHardwareStatus;
    }
    
    public void setAssetsHardwareStatus(String assetsHardwareStatus) {
        this.assetsHardwareStatus = assetsHardwareStatus;
    }




}


