package com.smart.models;
// Generated Apr 25, 2016 10:55:45 AM by Hibernate Tools 5.0.0.CR1



/**
 * AssetsSoftware generated by hbm2java
 */
public class AssetsSoftware  implements java.io.Serializable {


     private Integer assetSoftwareId;
     private String version;
     private String asset;
     private String vendor;
     private String datePurchase;
     private String licenseType;
     private String status;
     private String user;
     private String division;
     private String comments;
     private String platform;
     private String location;
     private String seats;

    public AssetsSoftware() {
    }

	
    public AssetsSoftware(String asset, String vendor, String licenseType) {
        this.asset = asset;
        this.vendor = vendor;
        this.licenseType = licenseType;
    }
    public AssetsSoftware(String asset, String vendor, String datePurchase, String licenseType, String status, String user, String division, String comments, String platform, String location, String seats) {
       this.asset = asset;
       this.vendor = vendor;
       this.datePurchase = datePurchase;
       this.licenseType = licenseType;
       this.status = status;
       this.user = user;
       this.division = division;
       this.comments = comments;
       this.platform = platform;
       this.location = location;
       this.seats = seats;
    }
   
    public Integer getAssetSoftwareId() {
        return this.assetSoftwareId;
    }
    
    public void setAssetSoftwareId(Integer assetSoftwareId) {
        this.assetSoftwareId = assetSoftwareId;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public String getAsset() {
        return this.asset;
    }
    
    public void setAsset(String asset) {
        this.asset = asset;
    }
    public String getVendor() {
        return this.vendor;
    }
    
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }
    public String getDatePurchase() {
        return this.datePurchase;
    }
    
    public void setDatePurchase(String datePurchase) {
        this.datePurchase = datePurchase;
    }
    public String getLicenseType() {
        return this.licenseType;
    }
    
    public void setLicenseType(String licenseType) {
        this.licenseType = licenseType;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getDivision() {
        return this.division;
    }
    
    public void setDivision(String division) {
        this.division = division;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public String getPlatform() {
        return this.platform;
    }
    
    public void setPlatform(String platform) {
        this.platform = platform;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getSeats() {
        return this.seats;
    }
    
    public void setSeats(String seats) {
        this.seats = seats;
    }




}


