package com.smart.models;
// Generated Apr 25, 2016 10:55:45 AM by Hibernate Tools 5.0.0.CR1



/**
 * AssetsHardwareType generated by hbm2java
 */
public class AssetsHardwareType  implements java.io.Serializable {


     private Integer id;
     private String assetsHardwareType;
     private String comments;

    public AssetsHardwareType() {
    }

	
    public AssetsHardwareType(String assetsHardwareType) {
        this.assetsHardwareType = assetsHardwareType;
    }
    public AssetsHardwareType(String assetsHardwareType, String comments) {
       this.assetsHardwareType = assetsHardwareType;
       this.comments = comments;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAssetsHardwareType() {
        return this.assetsHardwareType;
    }
    
    public void setAssetsHardwareType(String assetsHardwareType) {
        this.assetsHardwareType = assetsHardwareType;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


