package com.smart.models;
// Generated Apr 25, 2016 10:55:45 AM by Hibernate Tools 5.0.0.CR1



/**
 * AssetsSoftwareLicense generated by hbm2java
 */
public class AssetsSoftwareLicense  implements java.io.Serializable {


     private Integer id;
     private String assetsSoftwareLicense;

    public AssetsSoftwareLicense() {
    }

    public AssetsSoftwareLicense(String assetsSoftwareLicense) {
       this.assetsSoftwareLicense = assetsSoftwareLicense;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAssetsSoftwareLicense() {
        return this.assetsSoftwareLicense;
    }
    
    public void setAssetsSoftwareLicense(String assetsSoftwareLicense) {
        this.assetsSoftwareLicense = assetsSoftwareLicense;
    }




}


