package com.smart.models;
// Generated Apr 25, 2016 10:55:45 AM by Hibernate Tools 5.0.0.CR1



/**
 * AssetsHardware generated by hbm2java
 */
public class AssetsHardware  implements java.io.Serializable {


     private Integer assetHardwareId;
     private String assetType;
     private String vendor;
     private String model;
     private String serialnumber;
     private String assetTag;
     private String purchaseOrder;
     private String location;
     private String datePurchase;
     private String dateDecomission;
     private String status;
     private String user;
     private String division;
     private String platform;
     private String comments;
     private Integer monitorSize;
     private String warranty;
     private String cube;
     private String fieldAddress;
     private String userAccount;

    public AssetsHardware() {
    }

	
    public AssetsHardware(String vendor, String model) {
        this.vendor = vendor;
        this.model = model;
    }
    public AssetsHardware(String assetType, String vendor, String model, String serialnumber, String assetTag, String purchaseOrder, String location, String datePurchase, String dateDecomission, String status, String user, String division, String platform, String comments, Integer monitorSize, String warranty, String cube, String fieldAddress, String userAccount) {
       this.assetType = assetType;
       this.vendor = vendor;
       this.model = model;
       this.serialnumber = serialnumber;
       this.assetTag = assetTag;
       this.purchaseOrder = purchaseOrder;
       this.location = location;
       this.datePurchase = datePurchase;
       this.dateDecomission = dateDecomission;
       this.status = status;
       this.user = user;
       this.division = division;
       this.platform = platform;
       this.comments = comments;
       this.monitorSize = monitorSize;
       this.warranty = warranty;
       this.cube = cube;
       this.fieldAddress = fieldAddress;
       this.userAccount = userAccount;
    }
   
    public Integer getAssetHardwareId() {
        return this.assetHardwareId;
    }
    
    public void setAssetHardwareId(Integer assetHardwareId) {
        this.assetHardwareId = assetHardwareId;
    }
    public String getAssetType() {
        return this.assetType;
    }
    
    public void setAssetType(String assetType) {
        this.assetType = assetType;
    }
    public String getVendor() {
        return this.vendor;
    }
    
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getSerialnumber() {
        return this.serialnumber;
    }
    
    public void setSerialnumber(String serialnumber) {
        this.serialnumber = serialnumber;
    }
    public String getAssetTag() {
        return this.assetTag;
    }
    
    public void setAssetTag(String assetTag) {
        this.assetTag = assetTag;
    }
    public String getPurchaseOrder() {
        return this.purchaseOrder;
    }
    
    public void setPurchaseOrder(String purchaseOrder) {
        this.purchaseOrder = purchaseOrder;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getDatePurchase() {
        return this.datePurchase;
    }
    
    public void setDatePurchase(String datePurchase) {
        this.datePurchase = datePurchase;
    }
    public String getDateDecomission() {
        return this.dateDecomission;
    }
    
    public void setDateDecomission(String dateDecomission) {
        this.dateDecomission = dateDecomission;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getDivision() {
        return this.division;
    }
    
    public void setDivision(String division) {
        this.division = division;
    }
    public String getPlatform() {
        return this.platform;
    }
    
    public void setPlatform(String platform) {
        this.platform = platform;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public Integer getMonitorSize() {
        return this.monitorSize;
    }
    
    public void setMonitorSize(Integer monitorSize) {
        this.monitorSize = monitorSize;
    }
    public String getWarranty() {
        return this.warranty;
    }
    
    public void setWarranty(String warranty) {
        this.warranty = warranty;
    }
    public String getCube() {
        return this.cube;
    }
    
    public void setCube(String cube) {
        this.cube = cube;
    }
    public String getFieldAddress() {
        return this.fieldAddress;
    }
    
    public void setFieldAddress(String fieldAddress) {
        this.fieldAddress = fieldAddress;
    }
    public String getUserAccount() {
        return this.userAccount;
    }
    
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount;
    }




}


