package com.smart.models;
// Generated Apr 25, 2016 10:55:45 AM by Hibernate Tools 5.0.0.CR1



/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {


     private Integer companyId;
     private String companyName;

    public Company() {
    }

    public Company(String companyName) {
       this.companyName = companyName;
    }
   
    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }




}


