package com.smart.models;
// Generated Apr 25, 2016 10:55:45 AM by Hibernate Tools 5.0.0.CR1



/**
 * Division generated by hbm2java
 */
public class Division  implements java.io.Serializable {


     private Integer id;
     private String division;
     private String comments;

    public Division() {
    }

	
    public Division(String division) {
        this.division = division;
    }
    public Division(String division, String comments) {
       this.division = division;
       this.comments = comments;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDivision() {
        return this.division;
    }
    
    public void setDivision(String division) {
        this.division = division;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


