package com.smart.models;
// Generated Apr 25, 2016 10:55:45 AM by Hibernate Tools 5.0.0.CR1



/**
 * VendorsSoftware generated by hbm2java
 */
public class VendorsSoftware  implements java.io.Serializable {


     private Integer vendorId;
     private String vendor;
     private String comments;

    public VendorsSoftware() {
    }

	
    public VendorsSoftware(String vendor) {
        this.vendor = vendor;
    }
    public VendorsSoftware(String vendor, String comments) {
       this.vendor = vendor;
       this.comments = comments;
    }
   
    public Integer getVendorId() {
        return this.vendorId;
    }
    
    public void setVendorId(Integer vendorId) {
        this.vendorId = vendorId;
    }
    public String getVendor() {
        return this.vendor;
    }
    
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


